### ISSUE TITLE
Gaia.launch_job doesn't work.

### ISSUE THREAD

**Issue by tlarbgjs01** [astropy/astroquery#1475]
I'm querying DR2 data with launch_job.
After a minute, it shows error messages below.
I thought this was because of my computer's error.
So, I tried with another computer by installing python and astroquery from the beginning, but it failed too.
Even I tried example 1.4 of GAIA TAP+ astroquery document, it failed.
[gaia tap+ document](https://astroquery.readthedocs.io/en/latest/gaia/gaia.html)
Is it wrong with my code or computer or error of astroquery?

Traceback (most recent call last):
  File "C:\Users\tlarb\OneDrive\바탕 화면\gaia query.py", line 16, in <module>
    job = Gaia.launch_job("select top 100 solution_id,ref_epoch,ra_dec_corr,astrometric_n_obs_al,matched_observations,duplicated_source,phot_variable_flag from gaiadr1.gaia_source order by source_id")
  File "C:\Users\tlarb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\astroquery\gaia\core.py", line 116, in launch_job
    upload_table_name=upload_table_name)
  File "C:\Users\tlarb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\astroquery\utils\tap\core.py", line 248, in launch_job
    results = utils.read_http_response(response, output_format)
  File "C:\Users\tlarb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\astroquery\utils\tap\xmlparser\utils.py", line 42, in read_http_response
    result = APTable.read(data, format=astropyFormat)
  File "C:\Users\tlarb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\astropy\table\table.py", line 2550, in read
    out = io_registry.read(cls, *args, **kwargs)
  File "C:\Users\tlarb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\astropy\io\registry.py", line 517, in read
    data = reader(*args, **kwargs)
  File "C:\Users\tlarb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\astropy\io\votable\connect.py", line 73, in read_table_votable
    input = parse(input, table_id=table_id)
  File "C:\Users\tlarb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\astropy\io\votable\table.py", line 137, in parse
    config=config, pos=(1, 1)).parse(iterator, config)
  File "C:\Users\tlarb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\astropy\io\votable\tree.py", line 3341, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:0: no element found

**Comment by keflavich** [comment]
@tlarbgjs01 Did the problem resolve itself?

**Comment by tlarbgjs01** [comment]
Sorry for late reply.

I tried with other internet services and locations. Also, I reinstalled. But it didn't work too.
It lasted for some days.
By the way, the fun thing is that it was solved and worked well again...
