### ISSUE TITLE
Astropy's testing framework is not working properly with astroquery

### ISSUE THREAD

**Issue by jaladh-singhal** [astropy/astroquery#1610]
Hello team, 
Thanks for the great work you people are doing. Lately there has been some problems when I am running tests for the [new service](https://github.com/astropy/astroquery/pull/1498) I'm adding.

Whenever I run my tests with `python setup.py test`, it fails with following error:
```
running test
installing to temporary directory: /tmp/astroquery-test-9n93n41v
no previously-included directories found matching 'build'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/api'
no previously-included directories found matching 'astropy_helpers/build'
warning: no previously-included files matching '*.o' found anywhere in distribution
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jals/miniconda3/envs/astrqry/lib/python3.7/site-packages/astropy/tests/runner.py", line 261, in test
    return runner.run_tests(**kwargs)
  File "/home/jals/miniconda3/envs/astrqry/lib/python3.7/site-packages/astropy/tests/runner.py", line 606, in run_tests
    return super().run_tests(**kwargs)
  File "/home/jals/miniconda3/envs/astrqry/lib/python3.7/site-packages/astropy/tests/runner.py", line 243, in run_tests
    return pytest.main(args=args, plugins=plugins)
  File ".eggs/pytest-5.0.0-py3.7.egg/_pytest/config/__init__.py", line 55, in main
    config = _prepareconfig(args, plugins)
  File ".eggs/pytest-5.0.0-py3.7.egg/_pytest/config/__init__.py", line 200, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File ".eggs/pluggy-0.12.0-py3.7.egg/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File ".eggs/pluggy-0.12.0-py3.7.egg/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File ".eggs/pluggy-0.12.0-py3.7.egg/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File ".eggs/pluggy-0.12.0-py3.7.egg/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File ".eggs/pytest-5.0.0-py3.7.egg/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File ".eggs/pluggy-0.12.0-py3.7.egg/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File ".eggs/pluggy-0.12.0-py3.7.egg/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File ".eggs/pytest-5.0.0-py3.7.egg/_pytest/config/__init__.py", line 661, in pytest_cmdline_parse
    self.parse(args)
  File ".eggs/pytest-5.0.0-py3.7.egg/_pytest/config/__init__.py", line 869, in parse
    self._preparse(args, addopts=addopts)
  File ".eggs/pytest-5.0.0-py3.7.egg/_pytest/config/__init__.py", line 815, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File ".eggs/pluggy-0.12.0-py3.7.egg/pluggy/manager.py", line 292, in load_setuptools_entrypoints
    plugin = ep.load()
  File ".eggs/importlib_metadata-0.18-py3.7.egg/importlib_metadata/__init__.py", line 90, in load
    module = import_module(match.group('module'))
  File "/home/jals/miniconda3/envs/astrqry/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File ".eggs/pytest-5.0.0-py3.7.egg/_pytest/assertion/rewrite.py", line 149, in exec_module
    exec(co, module.__dict__)
  File "/home/jals/miniconda3/envs/astrqry/lib/python3.7/site-packages/hypothesis/__init__.py", line 36, in <module>
    from hypothesis.core import example, find, given, reproduce_failure, seed
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File ".eggs/pytest-5.0.0-py3.7.egg/_pytest/assertion/rewrite.py", line 149, in exec_module
    exec(co, module.__dict__)
  File "/home/jals/miniconda3/envs/astrqry/lib/python3.7/site-packages/hypothesis/core.py", line 73, in <module>
    from hypothesis.internal.conjecture.engine import ConjectureRunner, sort_key
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File ".eggs/pytest-5.0.0-py3.7.egg/_pytest/assertion/rewrite.py", line 149, in exec_module
    exec(co, module.__dict__)
  File "/home/jals/miniconda3/envs/astrqry/lib/python3.7/site-packages/hypothesis/internal/conjecture/engine.py", line 45, in <module>
    from hypothesis.internal.conjecture.shrinker import Shrinker, sort_key
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File ".eggs/pytest-5.0.0-py3.7.egg/_pytest/assertion/rewrite.py", line 149, in exec_module
    exec(co, module.__dict__)
  File "/home/jals/miniconda3/envs/astrqry/lib/python3.7/site-packages/hypothesis/internal/conjecture/shrinker.py", line 1444, in <module>
    @attr.s(slots=True, eq=False)
TypeError: attrs() got an unexpected keyword argument 'eq'
```
So I am currently using [`astropy.test()`](https://docs.astropy.org/en/stable/development/testguide.html#astropy-test) to run the tests which also has a strange problem. The tests passed (as expected) but only once, then they fail again with a `FileNotFoundError` (whose cause apparently seems the `_request` method):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jals/wrkspc/astroquery/astroquery/svo_fps/core.py", line 88, in get_transmission_data
    return self.data_from_svo(query, error_msg)
  File "/home/jals/wrkspc/astroquery/astroquery/svo_fps/core.py", line 39, in data_from_svo
    response = self._request("GET", self.SVO_MAIN_URL, params=query)
  File "/home/jals/wrkspc/astroquery/astroquery/query.py", line 247, in _request
    to_cache(response, query.request_file(self.cache_location))
  File "/home/jals/wrkspc/astroquery/astroquery/query.py", line 29, in to_cache
    with open(cache_file, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpra5b7ixvastropy_cache/astropy/astroquery/SvoFps/ddfd94d5989173752a360482210970b44153eef16615be56e355ab30.pickle'
```

The strange thing here is: when I restarted the python kernel, then they pass again on executing `astropy.test()` command, but only 1st time, not later! As @keflavich pointed out [here](https://github.com/astropy/astroquery/pull/1498#issuecomment-570058205), it may be a caching problem.

Please let me know if I'm missing some more details to share or anyhow I can help further?

**Comment by keflavich** [comment]
@bsipocz - do you have ideas on the former issue?  is that an astropy-helpers related thing (that will go away...?).

On the latter, this is clearly some kind of caching problem, but it's a weird one that I haven't yet figured out; it shouldn't look for that cache file unless that file exists.

**Comment by bsipocz** [comment]
Not sure where that's coming from, I haven't seen it elsewhere so I doubt it's helpers related. I'm rather short with time atm, but maybe I can come back to astroquery on the AAS hackday next week.

https://github.com/astropy/astroquery/pull/1607 resolves some other issues though.

**Comment by bsipocz** [comment]
This issue is now obsolete, I neither see issues with the testrunner, nor with pytest.
