### ISSUE TITLE
alma.login doesn't work

### ISSUE THREAD

**Issue by alipnick** [astropy/astroquery#1646]
During the update to ALMA's various systems today, it looks like CAS was changed (asa.alma.cl/cas) such that Alma.login() no longer works. It seems that the hidden metadata that is needed is now different. 

```python
>>> alma.login('alipnick')
alipnick, enter your ALMA password:

INFO: Authenticating alipnick on asa.alma.cl ... [astroquery.alma.core]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/da_data/lava-RHEL7/LAVA-RHEL7/lib/python2.7/site-packages/astroquery/query.py", line 338, in login
    self._authenticated = self._login(*args, **kwargs)
  File "/home/da_data/lava-RHEL7/LAVA-RHEL7/lib/python2.7/site-packages/astroquery/alma/core.py", line 566, in _login
    for kw in ('lt', '_eventId', 'execution')}
  File "/home/da_data/lava-RHEL7/LAVA-RHEL7/lib/python2.7/site-packages/astroquery/alma/core.py", line 566, in <dictcomp>
    for kw in ('lt', '_eventId', 'execution')}
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by bsipocz** [comment]
fixed by #1648
