### ISSUE TITLE
cadc.get_images() or cadc.query_region() times out 

### ISSUE THREAD

**Issue by falon3** [astropy/astroquery#1651]
When I do the same request from my local machine it times out, versus the same request made from our remote server which returns successfully. I have no idea why this would be the case since I have not changed anything on my end or the remote server end. I can make requests successfully to other astroquery libraries, just not Cadc. 

Error trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/falon/django_server/cirada/venv/lib/python3.6/site-packages/astroquery-0.3.10.dev5696-py3.6.egg/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/home/falon/django_server/cirada/venv/lib/python3.6/site-packages/astroquery-0.3.10.dev5696-py3.6.egg/astroquery/cadc/core.py", line 316, in get_images
    get_url_list, show_progress)
  File "/home/falon/django_server/cirada/venv/lib/python3.6/site-packages/astroquery-0.3.10.dev5696-py3.6.egg/astroquery/cadc/core.py", line 364, in get_images_async
    query_result = self.exec_sync(request_payload['query'])
  File "/home/falon/django_server/cirada/venv/lib/python3.6/site-packages/astroquery-0.3.10.dev5696-py3.6.egg/astroquery/cadc/core.py", line 575, in exec_sync
    response = self.cadctap.search(query, language='ADQL',
  File "/home/falon/django_server/cirada/venv/lib/python3.6/site-packages/astroquery-0.3.10.dev5696-py3.6.egg/astroquery/cadc/core.py", line 109, in cadctap
    self.baseurl = get_access_url(self.CADCTAP_SERVICE_URI)
  File "/home/falon/django_server/cirada/venv/lib/python3.6/site-packages/astroquery-0.3.10.dev5696-py3.6.egg/astroquery/cadc/core.py", line 765, in get_access_url
    response = requests.get(conf.CADC_REGISTRY_URL)
  File "/home/falon/django_server/cirada/venv/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/falon/django_server/cirada/venv/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/falon/django_server/cirada/venv/lib/python3.6/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/falon/django_server/cirada/venv/lib/python3.6/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/falon/django_server/cirada/venv/lib/python3.6/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca', port=80): Max retries exceeded with url: /reg/resource-caps (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7efc42234c88>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

**Comment by bsipocz** [comment]
cc @andamian

**Comment by andamian** [comment]
@falon3 - we (CADC) have experienced some network problems recently, which now have been fixed. Please give it another try and let me know if problems persist.

Thank you.

**Comment by pllim** [comment]
While investigating #1672 , I see a similar problem that affects one of the `cadc` remote data tests. I can reproduce it locally like this but not consistently:
```python
import time
from astroquery.cadc import Cadc

cadc = Cadc()

# I was trying to time it but you still see the same error without the timing part
t1 = time.time();  tables = cadc.get_tables(); t2 = time.time()
```
```
.../cadc/core.py in get_tables(self, only_names, verbose)
    529             return list(table_set.keys())
    530         else:
--> 531             return list(table_set.values())
    532 
    533     def get_table(self, table, verbose=None):

.../pyvo/dal/vosi.py in values(self)
    185         """
    186         for name in self.keys():
--> 187             yield self._get_table(name)
    188 
    189     def items(self):

.../pyvo/dal/vosi.py in _get_table(self, name)
    156         if not table.columns and not table.foreignkeys:
    157             tables_url = '{}/{}'.format(self._endpoint_url, name)
--> 158             response = self._get_table_file(tables_url)
    159 
    160             try:

.../pyvo/utils/decorators.py in wrapper(*args, **kwargs)
     18     @wraps(func)
     19     def wrapper(*args, **kwargs):
---> 20         response = func(*args, **kwargs)
     21         response.raw.read = partial(response.raw.read, decode_content=True)
     22         return response

.../pyvo/dal/vosi.py in _get_table_file(self, tables_url)
    170     @response_decode_content
    171     def _get_table_file(self, tables_url):
--> 172         return self._session.get(tables_url, stream=True)
    173 
    174     def keys(self):

.../requests/sessions.py in get(self, url, **kwargs)
    544 
    545         kwargs.setdefault('allow_redirects', True)
--> 546         return self.request('GET', url, **kwargs)
    547 
    548     def options(self, url, **kwargs):

.../requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    531         }
    532         send_kwargs.update(settings)
--> 533         resp = self.send(prep, **send_kwargs)
    534 
    535         return resp

.../requests/sessions.py in send(self, request, **kwargs)
    644 
    645         # Send the request
--> 646         r = adapter.send(request, **kwargs)
    647 
    648         # Total elapsed time of the request (approximately)

.../requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    512             if isinstance(e.reason, _SSLError):
    513                 # This branch is for urllib3 v1.22 and later.
--> 514                 raise SSLError(e, request=request)
    515 
    516             raise ConnectionError(e, request=request)

SSLError: HTTPSConnectionPool(host='www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca', port=443): Max retries exceeded with url: /argus//tables/caom2.Plane (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))
```

I was using `pyvo` 1.0 along with dev versions of `astropy` and `astroquery`.
