### ISSUE TITLE
Pull table from Vizier catalog with specific columns request

### ISSUE THREAD

**Issue by timstone-astro** [astropy/astroquery#1691]
Attempting to pull spectrum information from Vizier catalog VI/69. The following code works, but does not return the columns I need:

```
>>> from astroquery.vizier import Vizier
>>> v = Vizier()
>>> catalog_list = v.find_catalogs('VI/69')
>>> catalogs = v.get_catalogs(catalog_list.keys())
```

When adding columns to the Vizier instantiation:

```
>>> from astroquery.vizier import Vizier
>>> v = Vizier(columns=['ION', 'lambda','Int1'])
>>> catalog_list = v.find_catalogs('VI/69')
>>> catalogs = v.get_catalogs(catalog_list.keys())
E:\Program Files\Python\Python38\lib\site-packages\astroquery\vizier\core.py:717: UserWarning: VOTABLE parsing raised exception: a bytes-like object is required, not 'tuple'
  warnings.warn("VOTABLE parsing raised exception: {0}".format(ex))
Traceback (most recent call last):
  File "E:\Program Files\Python\Python38\lib\site-packages\astroquery\vizier\core.py", line 715, in parse_vizier_votable
    vo_tree = votable.parse(tf, pedantic=False, invalid='exception')
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\utils\decorators.py", line 535, in wrapper
    return function(*args, **kwargs)
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\table.py", line 166, in parse
    return tree.VOTableFile(
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\tree.py", line 3567, in parse
    tag_mapping.get(tag, self._add_unknown_tag)(
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\tree.py", line 3478, in _add_resource
    resource.parse(self, iterator, config)
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\tree.py", line 3279, in parse
    tag_mapping.get(tag, self._add_unknown_tag)(
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\tree.py", line 3225, in _add_table
    table.parse(iterator, config)
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\tree.py", line 2499, in parse
    self.array = self._parse_tabledata(
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\tree.py", line 2651, in _parse_tabledata
    array[numrows:] = array_chunk
  File "E:\Program Files\Python\Python38\lib\site-packages\numpy\ma\core.py", line 3343, in __setitem__
    _data[indx] = dval
TypeError: a bytes-like object is required, not 'tuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Program Files\Python\Python38\lib\site-packages\astroquery\vizier\core.py", line 647, in _parse_result
    return parse_vizier_votable(
  File "E:\Program Files\Python\Python38\lib\site-packages\astroquery\vizier\core.py", line 718, in parse_vizier_votable
    vo_tree = votable.parse(tf, pedantic=False, invalid='mask')
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\utils\decorators.py", line 535, in wrapper
    return function(*args, **kwargs)
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\table.py", line 166, in parse
    return tree.VOTableFile(
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\tree.py", line 3567, in parse
    tag_mapping.get(tag, self._add_unknown_tag)(
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\tree.py", line 3478, in _add_resource
    resource.parse(self, iterator, config)
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\tree.py", line 3279, in parse
    tag_mapping.get(tag, self._add_unknown_tag)(
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\tree.py", line 3225, in _add_table
    table.parse(iterator, config)
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\tree.py", line 2499, in parse
    self.array = self._parse_tabledata(
  File "E:\Program Files\Python\Python38\lib\site-packages\astropy\io\votable\tree.py", line 2651, in _parse_tabledata
    array[numrows:] = array_chunk
  File "E:\Program Files\Python\Python38\lib\site-packages\numpy\ma\core.py", line 3343, in __setitem__
    _data[indx] = dval
TypeError: a bytes-like object is required, not 'tuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Program Files\Python\Python38\lib\site-packages\astroquery\utils\class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "E:\Program Files\Python\Python38\lib\site-packages\astroquery\utils\process_asyncs.py", line 29, in newmethod
    result = self._parse_result(response, verbose=verbose)
  File "E:\Program Files\Python\Python38\lib\site-packages\astroquery\vizier\core.py", line 653, in _parse_result
    raise TableParseError("Failed to parse VIZIER result! The "
astroquery.exceptions.TableParseError: Failed to parse VIZIER result! The raw response can be found in self.response, and the error in self.table_parse_error. The attempted parsed result is in self.parsed_result.
 Exception: a bytes-like object is required, not 'tuple'
```

Perhaps I'm doing this incorrectly, but fiddler shows the response with the votable coming back with the specified columns. The failure is down in astropy votable parsing. I've given it a half day of trying to figure out what's going on. Am I doing something wrong?

**Comment by keflavich** [comment]
This looks like it could be a problem in the underlying votable; we've encountered such issues before.

**Comment by keflavich** [comment]
This is the response you got:
```
<?xml version="1.0" encoding="UTF-8"?>
<VOTABLE version="1.4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://www.ivoa.net/xml/VOTable/v1.3"
  xsi:schemaLocation="http://www.ivoa.net/xml/VOTable/v1.3 http://www.ivoa.net/xml/VOTable/v1.3">
 <DESCRIPTION>
   VizieR Astronomical Server vizier.u-strasbg.fr
    Date: 2020-04-01T15:46:56 [V1.99+ (14-Oct-2013)]
   Explanations and Statistics of UCDs:			See LINK below
   In case of problem, please report to:	cds-question@unistra.fr
   In this version, NULL integer columns are written as an empty string
   &lt;TD&gt;&lt;/TD&gt;, explicitely possible from VOTable-1.3
 </DESCRIPTION>
<!-- VOTable description at http://www.ivoa.net/Documents/latest/VOT.html -->
<INFO ID="VERSION" name="votable-version" value="1.99+ (14-Oct-2013)"/>
<INFO ID="Ref" name="-ref" value="VOTx43067"/>
<INFO name="-out.form" value="mini"/>
<INFO ID="MaxTuples" name="-out.max" value="50"/>
<INFO name="queryParameters" value="5">
-oc.form=d
-source=VI/69
-out=['ION', 'lambda', 'Int1', 'ION', 'lambda', 'Int1']
-out.add=ION,lambda,Int1,ION,lambda,Int1
-out.max=50
</INFO>

<RESOURCE ID="yCat_6069" name="VI/69">
  <DESCRIPTION>Atomic Spectral Line List (Hirata+ 1995)</DESCRIPTION>
  <TABLE ID="VI_69_catalog" name="VI/69/catalog">
    <DESCRIPTION>The catalogue of Atomic Spectral Lines</DESCRIPTION>
    <!-- Definitions of GROUPs and FIELDs -->
    <FIELD name="ION" ucd="AT_ION_ID" datatype="short" width="4">
      <DESCRIPTION>[101/9202] Ion number (e.g. 2602 for Fe II)</DESCRIPTION>
    </FIELD>
    <FIELD name="lambda" ucd="SPECT_WAVELENGTH_MISC" datatype="double" width="10" precision="4" unit="nm">
      <DESCRIPTION>Wavelength in nanometres (10Angstroems)</DESCRIPTION>
    </FIELD>
    <FIELD name="Int1" ucd="AT_INTENSITY" datatype="char" arraysize="6*">
      <DESCRIPTION>Laboratory intensity 1 (6)</DESCRIPTION>
    </FIELD>
<DATA><TABLEDATA>
<TR><TD>908</TD><TD>1.3143</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.3185</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.3244</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.3334</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.3488</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.3495</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.3781</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.3792</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4264</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4267</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4272</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4277</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4284</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4291</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4301</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4313</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4327</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4346</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4372</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4372</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4372</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4406</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4406</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4406</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4454</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4454</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4454</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.4458</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.4487</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4524</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4524</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4524</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4634</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4634</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4634</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4821</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4821</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.4821</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.5008</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.5008</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.5046</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.5046</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.5076</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.5155</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.5176</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.5176</TD><TD></TD></TR>
<TR><TD>808</TD><TD>1.5176</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.5224</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.5246</TD><TD></TD></TR>
<TR><TD>908</TD><TD>1.5286</TD><TD></TD></TR>
      </TABLEDATA>
    </DATA>
  </TABLE>
  <TABLE ID="VI_69_refs" name="VI/69/refs">
    <DESCRIPTION>The references</DESCRIPTION>
    <!-- Definitions of GROUPs and FIELDs -->
<DATA><TABLEDATA>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
<TR></TR>
</TABLEDATA></DATA>
<INFO name="matches" value="100">matching records</INFO>

<INFO name="Warning" value="Column '['ION', 'lambda', 'Int1', 'ION', 'lambda', 'Int1']' unknown in 'VI/69/catalog'"/>
<INFO name="Warning" value="truncated result (maxtup=50)"/><INFO name="QUERY_STATUS" value="OVERFLOW">truncated result (maxtup=50)</INFO>

<INFO name="Warning" value="Can't build column '_ION'"/>
<INFO name="Warning" value="Column 'ION' can'be created (Can't build column)"/>
<INFO name="Warning" value="Can't build column '_lambda'"/>
<INFO name="Warning" value="Column 'lambda' can'be created (Can't build column)"/>
<INFO name="Warning" value="Can't build column '_Int1'"/>
<INFO name="Warning" value="Column 'Int1' can'be created (Can't build column)"/>
<INFO name="Warning" value="Column '['ION', 'lambda', 'Int1', 'ION', 'lambda', 'Int1']' unknown in 'VI/69/refs'"/>
<INFO name="Warning" value="truncated result (maxtup=50)"/><INFO name="QUERY_STATUS" value="OVERFLOW">truncated result (maxtup=50)</INFO>

  </TABLE>
</RESOURCE>
</VOTABLE>
```

This looks like a problem with the underlying table.

**Comment by keflavich** [comment]
Huh, no, it looks like there are duplicate columns being requested...

**Comment by keflavich** [comment]
There is an astroquery bug here, but fixing said bug (#1692) doesn't solve the issue; it looks like a real problem with the table.

**Comment by timstone-astro** [comment]
I concluded it was likely a problem in the returned table, but couldn't isolate the problem. I've worked around by invoking the web service directly and getting a tsv rather than a votable back.

**Comment by jwoillez** [comment]
>>> from astroquery.vizier import Vizier
>>> v = Vizier(columns=['ION', 'lambda','Int1'])
>>> c = v.get_catalogs('VI/69')

Catalog `VI/69` contains two tables: `VI/69/catalog` and `VI/69/refs`. Both tables are filtered to only return the columns specified. Since only `VI/69/catalog` contains these columns, the table returned for `VI/69/refs` has no columns at all, and the parsing by `astropy.table.Table` goes wrong. Per the VOTable standard a table cannot have zero column. See "An empty table without any FIELD/PARAM should not be acceptable" in http://www.ivoa.net/xml/VOTable/VOTable-1.4.xsd. This is probably the reason why the parsing fails. It's a corner case, and CDS is probably doing the most sensible thing to do in this situation: return a table with no column but with the meta data that states that the requested columns cannot be created.

@keflavich @bsipocz Where would go from here?

**Comment by keflavich** [comment]
I don't know... it would be good if we could catch these cases based on their metadata before sending them to astropy's table parsing to fail.  That's a lot of work for this corner, though.

**Comment by jwoillez** [comment]
As you can see, I'm trying a trivial workaround in the votable parser of astropy. Let's see how this is received.
