### ISSUE TITLE
Observation.download_product: Unable to use the curl_flag option

### ISSUE THREAD

**Issue by ccossou** [astropy/astroquery#1755]
To replicate this bug, I try to download all products of a given proposal:
```python
obs_table = Observations.query_criteria(proposal_id="NHJRD")
obsids = obs_table["obsid"]

data_products = Observations.get_product_list(obsids)

manifest = Observations.download_products(data_products, curl_flag=True)
```

The error I get is:
```
m = Observations.download_products(data_products_by_id, curl_flag=True)
Downloading URL https://mast.stsci.edu/api/v0.1/Download/bundle.sh to ./mastDownload_20200701120118.sh ... [Failed]
Traceback (most recent call last):
  File "/local/home/ccossou/pycharm/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/local/home/ccossou/virtualenv/miricap/lib/python3.7/site-packages/astroquery/mast/observations.py", line 695, in download_products
    manifest = self._download_curl_script(products, download_dir)
  File "/local/home/ccossou/virtualenv/miricap/lib/python3.7/site-packages/astroquery/mast/observations.py", line 616, in _download_curl_script
    local_path, data=url_list, method="POST")
  File "/local/home/ccossou/virtualenv/miricap/lib/python3.7/site-packages/astroquery/query.py", line 379, in _download_file
    for block in response.iter_content(blocksize):
  File "/local/home/ccossou/virtualenv/miricap/lib/python3.7/site-packages/requests/models.py", line 754, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

The file only contain the following value:
```
#!/bin/b
```

I could download the files directly so I think this is related to the script generation/download process and not the files I query directly.

**Comment by ceb8** [comment]
@ccossou This seems to be a result of a hiccup in your internet connection, do you still get this error? I was able to download the curl file just now when I tried, so please let me know if you are still seeing the problem behavior.

**Comment by ccossou** [comment]
Indeed, it works now. What's weird is that I could replicate that multiple times and consistently got "#!/bin/b".

Thanks for your help. Closing

**Comment by ceb8** [comment]
@ccossou  Oh that is weird. Probably the disconnect was happening on our end then, although it's weird that it consistently succeeded in getting the first few bytes through. My guess would be it was some sort of unexpected down time manifesting weirdly, but if it happens again let us know.
