### ISSUE TITLE
shapely 1.7.1 causing windows CI failures

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1804]
The windows CI install is failing with the following error, while it was working before. The package is pulled in as an indirect dependency, I'll scale back or pin the version umber for the windows testing as a workaround.

shapely 1.7.1 was released today

```
Collecting shapely>=1.6

  Downloading Shapely-1.7.1.tar.gz (383 kB)

    ERROR: Command errored out with exit status 1:

     command: 'C:\tools\miniconda3\envs\test\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\travis\\AppData\\Local\\Temp\\pip-install-a6csizkd\\shapely\\setup.py'"'"'; __file__='"'"'C:\\Users\\travis\\AppData\\Local\\Temp\\pip-install-a6csizkd\\shapely\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\travis\AppData\Local\Temp\pip-pip-egg-info-w0iz65s4'

         cwd: C:\Users\travis\AppData\Local\Temp\pip-install-a6csizkd\shapely\

    Complete output (9 lines):

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "C:\Users\travis\AppData\Local\Temp\pip-install-a6csizkd\shapely\setup.py", line 85, in <module>

        from shapely._buildcfg import geos_version_string, geos_version, \

      File "C:\Users\travis\AppData\Local\Temp\pip-install-a6csizkd\shapely\shapely\_buildcfg.py", line 205, in <module>

        lgeos = CDLL("geos_c.dll")

      File "C:\tools\miniconda3\envs\test\lib\ctypes\__init__.py", line 364, in __init__

        self._handle = _dlopen(self._name, mode)

    OSError: [WinError 126] The specified module could not be found
```

**Comment by bsipocz** [comment]
Upstream release of windows wheels has fixed this.
