### ISSUE TITLE
Can not access GAIA data

### ISSUE THREAD

**Issue by iHD992** [astropy/astroquery#1981]
Code:
```python
import astropy.coordinates as coord
from astropy.table import QTable
import astropy.units as u
from astroquery.gaia import Gaia

query_text = '''SELECT TOP 512 ra, dec, parallax, pmra, pmdec, radial_velocity
FROM gaiadr2.gaia_source
WHERE parallax_over_error > 10 AND
    parallax > 0.16 AND
    radial_velocity IS NOT null
ORDER BY random_index
'''

job = Gaia.launch_job(query_text)
gaia_data = job.get_results()
gaia_data.write('gaia_data.fits')
```

Result:
```
Created TAP+ (v1.2.1) - Connection:
	Host: gea.esac.esa.int
	Use HTTPS: True
	Port: 443
	SSL Port: 443
Created TAP+ (v1.2.1) - Connection:
	Host: geadata.esac.esa.int
	Use HTTPS: True
	Port: 443
	SSL Port: 443
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\gaia.py", line 15, in <module>
    job = Gaia.launch_job(query_text)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\astroquery\utils\tap\core.py", line 339, in launch_job
    results = utils.read_http_response(response, output_format)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\astroquery\utils\tap\xmlparser\utils.py", line 42, in read_http_response
    result = APTable.read(data, format=astropyFormat)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\astropy\table\connect.py", line 61, in __call__
    out = registry.read(cls, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\astropy\io\registry.py", line 520, in read
    data = reader(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\astropy\io\votable\connect.py", line 116, in read_table_votable
    raise ValueError("No table found")
ValueError: No table found
```

**Comment by keflavich** [comment]
What result do you expect?  Are you sure your SQL query is valid?

**Comment by iHD992** [comment]
Indeed, the query is invalid. It seems the database structure has been changed since this tutorial has been written:
https://learn.astropy.org/rst-tutorials/gaia-galactic-orbits.html?highlight=filtertutorials

This query works: `query_text = '''SELECT TOP 512 ra, dec, parallax, pmra, pmdec
FROM gaiaedr3.gaia_source
WHERE parallax_over_error > 10 AND
    parallax > 0.16
ORDER BY random_index
'''`
