### ISSUE TITLE
Error using irsa catalogs

### ISSUE THREAD

**Issue by sklandrausis** [astropy/astroquery#2002]
>>> from astroquery.irsa import Irsa
>>> Irsa.list_catalogs()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/astroquery/irsa/core.py", line 425, in list_catalogs
    root = tree.fromstring(response.content)
  File "/usr/lib64/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 5, column 0

**Comment by keflavich** [comment]
I can't reproduce this exactly, but I got a timeout error from IRSA this morning:
```python
In [4]: from astroquery.irsa import Irsa
   ...: Irsa.list_catalogs()
Traceback (most recent call last):
  File "/home/adam/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/adam/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/adam/anaconda3/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/home/adam/anaconda3/lib/python3.7/http/client.py", line 330, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/home/adam/anaconda3/lib/python3.7/http/client.py", line 215, in parse_headers
    line = fp.readline(_MAXLINE + 1)
  File "/home/adam/anaconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/adam/anaconda3/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/home/adam/anaconda3/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
timeout: The read operation timed out

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/adam/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/adam/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/adam/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/adam/anaconda3/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/adam/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/adam/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/adam/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
ReadTimeoutError: HTTPSConnectionPool(host='irsa.ipac.caltech.edu', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<ipython-input-4-8b80c4b77a83>", line 2, in <module>
    Irsa.list_catalogs()
  File "/home/adam/repos/astroquery/astroquery/irsa/core.py", line 425, in list_catalogs
    params=dict(mode='xml'), timeout=Irsa.TIMEOUT)
  File "/home/adam/repos/astroquery/astroquery/query.py", line 263, in _request
    json=json)
  File "/home/adam/repos/astroquery/astroquery/query.py", line 71, in request
    json=json)
  File "/home/adam/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/adam/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/adam/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='irsa.ipac.caltech.edu', port=443): Read timed out. (read timeout=60)
```

**Comment by kfkaplan** [comment]
I have gotten the same error
```
In [1]: from astroquery.irsa import Irsa

In [2]: Irsa.print_catalogs()
Traceback (most recent call last):

  File "/Users/kkaplan1/conda/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-b55b683db431>", line 1, in <module>
    Irsa.print_catalogs()

  File "/Users/kkaplan1/conda/anaconda3/lib/python3.8/site-packages/astroquery/irsa/core.py", line 437, in print_catalogs
    catalogs = self.list_catalogs()

  File "/Users/kkaplan1/conda/anaconda3/lib/python3.8/site-packages/astroquery/irsa/core.py", line 425, in list_catalogs
    root = tree.fromstring(response.content)

  File "/Users/kkaplan1/conda/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)

  File "<string>", line unknown
ParseError: XML or text declaration not at start of entity: line 5, column 0

```

**Comment by bsipocz** [comment]
OK, I see the same error locally, and it all boils down to the response of `b'<?xml version="1.0"?>\n\n<Holdings archive="IRSA">\n\n<?xml version="1.0"?>\n<error> input string is too large to be copied to output buffer </error>\n'`

**Comment by bsipocz** [comment]
This has been resolved upstream. If you still see the issue, please clear the cache, e.g. delete `~/.astropy/cache/astroquery/Irsa`
