### ISSUE TITLE
Astroquery list catalogs error

### ISSUE THREAD

**Issue by astromark** [astropy/astroquery#2008]
### Description

When trying to list IRSA catalogs I receive a 'parse error'.

### Expected behavior

Receive a list of IRSA catalogs.

### Actual behavior

Received this traceback.
```python
Traceback (most recent call last):

  File "/home/mark/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-8cb2107cac93>", line 2, in <module>
    Irsa.list_catalogs()

  File "/home/mark/anaconda3/lib/python3.7/site-packages/astroquery/irsa/core.py", line 425, in list_catalogs
    root = tree.fromstring(response.content)

  File "/home/mark/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)

  File "<string>", line unknown
ParseError: XML or text declaration not at start of entity: line 5, column 0

```

### Steps to Reproduce

```python
from astroquery.irsa import Irsa                                        
Irsa.list_catalogs()    
```

### System Details
Linux-5.4.0-65-generic-x86_64-with-debian-bullseye-sid
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0]
Numpy 1.19.2
astropy 4.0.2
Scipy 1.5.2
Matplotlib 3.3.2
astroquery 0.4.1

**Comment by keflavich** [comment]
I confirm this is happening.  The error message is:
```
b'<?xml version="1.0"?>\n\n<Holdings archive="IRSA">\n\n<?xml version="1.0"?>\n<error> input string is too large to be copied to output buffer </error>\n'
```

**Comment by tamhanepd** [comment]
I can confirm. I am getting the same error.

```python
from astroquery.irsa import Irsa
Irsa.print_catalogs()
```

```python
Traceback (most recent call last):

 File "/home/prathamesh/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-51-b55b683db431>", line 1, in <module>
    Irsa.print_catalogs()'

  File "/home/prathamesh/.local/lib/python3.6/site-packages/astroquery/irsa/core.py", line 437, in print_catalogs
    catalogs = self.list_catalogs()

  File "/home/prathamesh/.local/lib/python3.6/site-packages/astroquery/irsa/core.py", line 425, in list_catalogs
    root = tree.fromstring(response.content)

  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)

  File "<string>", line unknown
ParseError: XML or text declaration not at start of entity: line 5, column 0
```

The `catalog` keyword is essential for `Irsa` queries. Are catalogue names listed somewhere else? I can find the descriptions on the IRSA website, but I don't know the keywords to be used in astroquery search.

**Comment by keflavich** [comment]
This is an upstream issue, it appears no longer possible to get XML display of the main Gator page.
https://irsa.ipac.caltech.edu/cgi-bin/Gator/nph-scan?mode=xml

**Comment by keflavich** [comment]
https://irsa.ipac.caltech.edu/applications/Gator/GatorAid/irsa/catlist.html documents how we are supposed to retrieve this data.  There is an ascii version (https://irsa.ipac.caltech.edu/cgi-bin/Gator/nph-scan?mode=ascii) that is documented on a different page (https://irsa.ipac.caltech.edu/applications/Gator/GatorAid/irsa/catsearch.html) we can use as a workaround.

**Comment by keflavich** [comment]
I've reported the issue upstream to IRSA.

**Comment by bsipocz** [comment]
This has been fixed upstream, so I'm closing the issue for now. Thanks for reporting!
