### ISSUE TITLE
No module named 'astropy._erfa.core'

### ISSUE THREAD

**Issue by RuiningZHAO** [astropy/astroquery#2031]
astropy==4.2
astroquery==0.4.1

When I import MPC from astroquery.mpc, a warning is raised
`WARNING: AstropyDeprecationWarning: The private astropy._erfa module has been made into its own package, pyerfa, which is a dependency of astropy and can be imported directly using "import erfa" [astropy._erfa]`

followed by an error.
```
Traceback (most recent call last):
  File "./test.py", line 22, in <module>
    from utils import *
  File "/home/rzhao/Documents/Projects/cometplan/utils.py", line 8, in <module>
    from astroquery.mpc import MPC
  File "/home/rzhao/anaconda3/lib/python3.7/site-packages/astroquery/mpc/__init__.py", line 44, in <module>
    from .core import MPC, MPCClass
  File "/home/rzhao/anaconda3/lib/python3.7/site-packages/astroquery/mpc/core.py", line 14, in <module>
    from astropy._erfa.core import ErfaWarning
ModuleNotFoundError: No module named 'astropy._erfa.core'
```
It can be fixed by replacing `from astropy._erfa.core import ErfaWarning` (line 14) in `astroquery/mpc/core.py` with `from erfa.core import ErfaWarning`

**Comment by bsipocz** [comment]
This has been fixed for a while, please install the latest version with ``pip install --pre astroquery``, you may also need to use `--use-deprecated=legacy-resolver `
