### ISSUE TITLE
astroquery not working on M1 Mac

### ISSUE THREAD

**Issue by ChopsKingsland** [astropy/astroquery#2033]
I am trying to use astroquery on an M1 Mac, and it just doesn't work. Firstly, to install astroquery, I had to open terminal with Rosetta (basically to emulate an Intel Mac, otherwise it wouldn't work). And now, my code won't run... My code is

```
from astroquery.jplhorizons import Horizons

planets = [199, 299, 301, 499, 599, 699, 799, 899, 999]
planetNames = ["Mercury", "Venus", "Moon", "Mars",
               "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"]


def getPlanetInfo(planet):
    obj = Horizons(id=planet, location='000', epochs=None, id_type='majorbody')
    eph = obj.ephemerides()
    return eph


eph = getPlanetInfo(planets[planetIndex])
percentageArcAZ = (eph['AZ'][0])/360  # find Azimuth
percentageArcEL = (eph['EL'][0])/360  # find Elevation
stepsNeededAZ = int(percentageArcAZ*512)  # 512 steps is 360degrees
stepsNeededEL = int(percentageArcEL*512)  # 512 steps is 360degrees

```

and the error I'm getting is

```
Traceback (most recent call last):
  File "/Users/*****/Documents/Python/*****/main.py", line 1, in <module>
    from astroquery.jplhorizons import Horizons
  File "/opt/homebrew/lib/python3.9/site-packages/astroquery/__init__.py", line 12, in <module>
    from ._astropy_init import *
  File "/opt/homebrew/lib/python3.9/site-packages/astroquery/_astropy_init.py", line 29, in <module>
    from astropy.config.configuration import (
  File "/opt/homebrew/lib/python3.9/site-packages/astropy/__init__.py", line 248, in <module>
    _initialize_astropy()
  File "/opt/homebrew/lib/python3.9/site-packages/astropy/__init__.py", line 200, in _initialize_astropy
    from .utils import _compiler
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/astropy/utils/_compiler.cpython-39-darwin.so, 2): no suitable image found.  Did find:
        /opt/homebrew/lib/python3.9/site-packages/astropy/utils/_compiler.cpython-39-darwin.so: mach-o, but wrong architecture
        /opt/homebrew/lib/python3.9/site-packages/astropy/utils/_compiler.cpython-39-darwin.so: mach-o, but wrong architecture
```

**Comment by bsipocz** [comment]
The error is coming from astropy and not astroquery, I'm transferring the issue there.
