### ISSUE TITLE
JPLSpec should use http, not https

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#2124]
JPL's servers don't support https, so queries sent with `verify=True` (the requests default) will fail.

**Comment by keflavich** [comment]
The tracebacks looked like:
```
Traceback (most recent call last):
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f98a961bc10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPSConnectionPool(host='spec.jpl.nasa.gov', port=443): Max retries exceeded with url: /cgi-bin/catform (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f98a961bc10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<ipython-input-196-d2faea246970>", line 1, in <module>
    JPLSpec.query_lines(218*u.GHz, 219*u.GHz, molecule='CH3COCH3')
  File "/home/adam/repos/astroquery/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/home/adam/repos/astroquery/astroquery/utils/process_asyncs.py", line 26, in newmethod
    response = getattr(self, async_method_name)(*args, **kwargs)
  File "/home/adam/repos/astroquery/astroquery/jplspec/core.py", line 123, in query_lines_async
    response = self._request(method='POST', url=self.URL, data=payload,
  File "/home/adam/repos/astroquery/astroquery/query.py", line 303, in _request
    response = query.request(self._session,
  File "/home/adam/repos/astroquery/astroquery/query.py", line 67, in request
    return session.request(self.method, self.url, params=self.params,
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/adam/anaconda3/envs/python3.9/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='spec.jpl.nasa.gov', port=443): Max retries exceeded with url: /cgi-bin/catform (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f98a961bc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
```


I thought this was an https-related error, but it seems to have been just a temporary error on the server.
