### ISSUE TITLE
ALMA: sia query doesn't accept coordinates

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#2240]
@andamian this looks like a bug in how `pyvo` is handlign the `pos` keyword (or, I don't understand what's expected, but in that case it's clearly a documentation issue)

```python
>>> from astroquery.alma import Alma
>>> from astropy import coordinates
>>> from astropy import units as u
>>> galactic_center = coordinates.SkyCoord(0*u.deg, 0*u.deg, frame='galactic')
>>> Alma.query_sia(pos=galactic_center, pol='XX')

Traceback (most recent call last):
  File "<ipython-input-3-cfb9f36d29ef>", line 1, in <module>
    Alma.query_sia(pos=galactic_center, pol='XX')
  File "/Users/adam/miniconda3/envs/python3.9/lib/python3.9/site-packages/astroquery/alma/core.py", line 406, in query_sia
    return self.sia.search(
  File "/Users/adam/miniconda3/envs/python3.9/lib/python3.9/site-packages/pyvo/dal/sia2.py", line 192, in search
    return SIAQuery(self.query_ep, pos=pos, band=band,
  File "/Users/adam/miniconda3/envs/python3.9/lib/python3.9/site-packages/pyvo/dal/sia2.py", line 265, in __init__
    self.pos.add(pp)
  File "/Users/adam/miniconda3/envs/python3.9/lib/python3.9/site-packages/pyvo/dal/params.py", line 255, in add
    if item in self:
  File "/Users/adam/miniconda3/envs/python3.9/lib/python3.9/site-packages/pyvo/dal/params.py", line 276, in __contains__
    return self.get_dal_format(item) in self.dal
  File "/Users/adam/miniconda3/envs/python3.9/lib/python3.9/site-packages/pyvo/dal/params.py", line 298, in get_dal_format
    self._validate_pos(val)
  File "/Users/adam/miniconda3/envs/python3.9/lib/python3.9/site-packages/pyvo/dal/params.py", line 319, in _validate_pos
    if len(pos) == 3:
  File "/Users/adam/repos/astropy/astropy/utils/shapes.py", line 209, in __len__
    raise TypeError("Scalar {!r} object has no len()"
TypeError: Scalar 'SkyCoord' object has no len()
```

**Comment by bsipocz** [comment]
If this is indeed a pyvo bug we can move the issue over to that repo.

**Comment by keflavich** [comment]
Agree.  I just don't know for sure yet.
