### ISSUE TITLE
ALMA downloader caches bad downloads

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#2241]
This is what happens after a bad download is cached:

```python
from astroquery.alma import Alma

Alma().download_files(['https://almascience.nrao.edu/dataPortal/member.uid___A001_X8a9_X26.J0510p1800_bp.spw25.mfs.I.pb.fits.gz',
   ...:  'https://almascience.nrao.edu/dataPortal/member.uid___A001_X8a9_X26.J0510p1800_bp.spw25.mfs.I.pbcor.fits',])
```
raises:
```python
Traceback (most recent call last):
  File "<ipython-input-2-86b2211f6631>", line 1, in <module>
    Alma().download_files(['https://almascience.nrao.edu/dataPortal/member.uid___A001_X8a9_X26.J0510p1800_bp.spw25.mfs.I.pb.fits.gz',
  File "/Users/adam/miniconda3/envs/python3.9/lib/python3.9/site-packages/astroquery/alma/core.py", line 714, in download_files
    check_filename = self._request('HEAD', fileLink, auth=auth,
  File "/Users/adam/miniconda3/envs/python3.9/lib/python3.9/site-packages/astroquery/query.py", line 311, in _request
    response = query.from_cache(self.cache_location)
  File "/Users/adam/miniconda3/envs/python3.9/lib/python3.9/site-packages/astroquery/query.py", line 109, in from_cache
    response = pickle.load(f)
  File "/Users/adam/repos/astropy/astropy/utils/collections.py", line 55, in extend
    self._assert(item)
  File "/Users/adam/repos/astropy/astropy/utils/collections.py", line 28, in _assert
    if not isinstance(x, self._types):
AttributeError: 'HomogeneousList' object has no attribute '_types'
```

As with other modules, we need to be more careful about _not_ caching failed queries.

**Comment by keflavich** [comment]
No idea.  Let's close it for now; if I get caching problems again w/ALMA, hopefully this will show up in my searches.
