### ISSUE TITLE
Behavior of Observations.download_products() when given an empty table

### ISSUE THREAD

**Issue by mdlpstsci** [astropy/astroquery#2636]
I have distilled a situation we have tripped on in our code provided as an example below.  Because it is a "distilled" situation, it looks like a silly example, but it gets the point across.

Bug or Feature?

=====
PREVIOUS SITUATION which worked in our code - no fuss and no muss.
astroquery  0.4.6    

bash-4.2$ python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from astroquery.mast import Observations
>>> from astropy.table import Table
>>> t = Table()
>>> manifest = Observations.download_products(t, mrp_only=False)
WARNING: NoResultsWarning: No products to download. [astroquery.mast.observations]
>>>

=====
NEW SITUATION which throws an exception.
astroquery                0.4.7.dev8438             dev_0    <develop>

Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)
bash-4.2$ python
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from astroquery.mast import Observations
>>> from astropy.table import Table
>>> t = Table()
>>> manifest = Observations.download_products(t, mrp_only=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mdelapena/repository/astroquery/astroquery/mast/observations.py", line 725, in download_products
    products = self._remove_duplicate_products(products)
  File "/home/mdelapena/repository/astroquery/astroquery/mast/observations.py", line 842, in _remove_duplicate_products
    unique_products = unique(data_products, keys="dataURI")
  File "/home/mdelapena/miniconda3/envs/caldp_20221010/lib/python3.9/site-packages/astropy/table/operations.py", line 841, in unique
    col = input_table[key]
  File "/home/mdelapena/miniconda3/envs/caldp_20221010/lib/python3.9/site-packages/astropy/table/table.py", line 1872, in __getitem__
    return self.columns[item]
  File "/home/mdelapena/miniconda3/envs/caldp_20221010/lib/python3.9/site-packages/astropy/table/table.py", line 246, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'dataURI'
>>>

**Comment by bsipocz** [comment]
I think getting an `InvalidQueryError` maybe appropriate here, as one should already have received a `NoResultsWarning` when they got that empty table back from an actual query. But the KeyError definitely feels like a bug.

**Comment by RilyndC** [comment]
Still reproduces on astroquery 0.4.11 (Python 3.14). The traceback has moved since this was filed, it's now utils.remove_duplicate_products in mast/utils.py rather than _remove_duplicate_products in observations.py, but the failure is the same KeyError: 'dataURI'.

Checked the two empty cases separately:

Table() with no columns raises KeyError at the dedup call in download_products.
Table({'dataURI': []}) with the column present and zero rows warns NoResultsWarning and returns cleanly.

filter_products handles a bare table fine and returns an empty Table, so the crash is specific to dedup requiring dataURI to exist. The existing if not len(products) check sits one line below the dedup call, so it's never reached in the no-column case.

Is anyone working on this? Happy to put a PR together if not. Would you still want InvalidQueryError for the missing-column case, keeping the zero-row case as a NoResultsWarning? And would the guard be better in download_products or inside remove_duplicate_products, since that's a shared util.

**Comment by bsipocz** [comment]
@RilyndC - Please leave mast related PR to the mast developer team, they are quite on top of the game.

**Comment by keflavich** [comment]
@RilyndC based on your last few interactions with astroquery, you are an AI bot submitting unsolicited changes.  If that is the case, please stop.
