### ISSUE TITLE
Astroquery.ipac.ned xml syntax error

### ISSUE THREAD

**Issue by mspeace49** [astropy/astroquery#2754]
Hi,
I am using astroquery to access data from e.g. SIMBAD, it works, but it returns errors when I do so for NED. Below is the error message I got.
I used astroquery.ned a few years ago and it worked fine, I dont know if the updated astroquery.ipac.ned has some problem? Could you please help me to look into this? Thanks in advance.

```
result_table = Ned.get_table("3C 273", table='positions')
Traceback (most recent call last):
  File "/home/nhannguyen/miniconda/envs/py38/lib/python3.8/site-packages/astroquery/ipac/ned/core.py", line 704, in _parse_result
    first_table = votable.parse(tf, verify='warn').get_first_table()
  File "/home/nhannguyen/miniconda/envs/py38/lib/python3.8/site-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/home/nhannguyen/miniconda/envs/py38/lib/python3.8/site-packages/astropy/io/votable/table.py", line 159, in parse
    return tree.VOTableFile(
  File "/home/nhannguyen/miniconda/envs/py38/lib/python3.8/site-packages/astropy/io/votable/tree.py", line 3572, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nhannguyen/miniconda/envs/py38/lib/python3.8/site-packages/astroquery/ipac/ned/core.py", line 574, in get_table
    result = self._parse_result(response, verbose=verbose)
  File "/home/nhannguyen/miniconda/envs/py38/lib/python3.8/site-packages/astroquery/ipac/ned/core.py", line 708, in _parse_result
    (is_valid, err_msg) = _check_ned_valid(response.content)
  File "/home/nhannguyen/miniconda/envs/py38/lib/python3.8/site-packages/astroquery/ipac/ned/core.py", line 749, in _check_ned_valid
    strdom = parseString(string)
  File "/home/nhannguyen/miniconda/envs/py38/lib/python3.8/xml/dom/minidom.py", line 1969, in parseString
    return expatbuilder.parseString(string)
  File "/home/nhannguyen/miniconda/envs/py38/lib/python3.8/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/home/nhannguyen/miniconda/envs/py38/lib/python3.8/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 49
![astroquery-error-xml](https://github.com/astropy/astroquery/assets/50931816/6b19f919-df5e-499a-a926-40a528f87e8c)
```

**Comment by mspeace49** [comment]
Hi,
Thanks a lot for your answer. I updated the latest version and now it works. 
Best regards.

**Comment by PeterKamphuis** [comment]
I have this issue in the latest version even after trying the listed suggestions:

```
> import astroquery
> astroquery.__version__
'0.4.11'
> from astroquery.ipac.ned import Ned
> Ned.clear_cache()
> result_table = Ned.get_table("3C 273", table='positions')
Traceback (most recent call last):
  File "/lib/python3.13/site-packages/astroquery/ipac/ned/core.py", line 704, in _parse_result
    first_table = votable.parse(tf, verify='warn').get_first_table()
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.13/site-packages/astropy/io/votable/table.py", line 164, in parse
    return tree.VOTableFile(config=config, pos=(1, 1)).parse(iterator, config)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/lib/python3.13/site-packages/astropy/io/votable/tree.py", line 4345, in parse
    for start, tag, data, pos in iterator:
                                 ^^^^^^^^
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<python-input-20>", line 1, in <module>
    result_table = Ned.get_table("3C 273", table='positions')
  File "/lib/python3.13/site-packages/astroquery/ipac/ned/core.py", line 574, in get_table
    result = self._parse_result(response, verbose=verbose)
  File "/lib/python3.13/site-packages/astroquery/ipac/ned/core.py", line 708, in _parse_result
    (is_valid, err_msg) = _check_ned_valid(response.content)
                          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/lib/python3.13/site-packages/astroquery/ipac/ned/core.py", line 749, in _check_ned_valid
    strdom = parseString(string)
  File "/usr/local/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/xml/dom/minidom.py", line 2016, in parseString
    return expatbuilder.parseString(string)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/xml/dom/expatbuilder.py", line 922, in parseString
    return builder.parseString(string)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/xml/dom/expatbuilder.py", line 220, in parseString
    parser.Parse(string, True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^
xml.parsers.expat.ExpatError: syntax error: line 1, column 49
```

If  install the current main  from github I get a 401 error for the same command:

```requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://ned.ipac.caltech.edu/cgi-bin/datasearch?of=xml_main&objname=NGC+224&search_type=Photometry&meas_type=bot```

**Comment by bsipocz** [comment]
I can't reproduce the failure, the example works for me both with the release and dev versions.

**Comment by PeterKamphuis** [comment]
Weird, I just tried again from home and now it works. So perhaps a firewall issue but I would not expect those errors for that.
