### ISSUE TITLE
Cryptic query failure for astroquery.ipac.ned

### ISSUE THREAD

**Issue by alexandergagliano** [astropy/astroquery#2765]
Hello, 

I'm trying to run the code listed on the [astroquery website ](https://astroquery.readthedocs.io/en/latest/ipac/ned/ned.html) to query a region in NED: 

```
from astropy import units as u
from astroquery.ipac.ned import Ned
result_table = Ned.query_region("3c273", radius=0.05 * u.deg)
```
When I do this, I get the following error message:

```
Traceback (most recent call last):
  File "/Users/alexgagliano/mambaforge/envs/testastroquery/lib/python3.10/site-packages/astroquery/ipac/ned/core.py", line 704, in _parse_result
    first_table = votable.parse(tf, verify='warn').get_first_table()
  File "/Users/alexgagliano/mambaforge/envs/testastroquery/lib/python3.10/site-packages/astropy/utils/decorators.py", line 604, in wrapper
    return function(*args, **kwargs)
  File "/Users/alexgagliano/mambaforge/envs/testastroquery/lib/python3.10/site-packages/astropy/io/votable/table.py", line 177, in parse
    return tree.VOTableFile(config=config, pos=(1, 1)).parse(iterator, config)
  File "/Users/alexgagliano/mambaforge/envs/testastroquery/lib/python3.10/site-packages/astropy/io/votable/tree.py", line 3858, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:49: syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexgagliano/mambaforge/envs/testastroquery/lib/python3.10/site-packages/astroquery/ipac/ned/core.py", line 144, in query_region
    result = self._parse_result(response, verbose=verbose)
  File "/Users/alexgagliano/mambaforge/envs/testastroquery/lib/python3.10/site-packages/astroquery/ipac/ned/core.py", line 708, in _parse_result
    (is_valid, err_msg) = _check_ned_valid(response.content)
  File "/Users/alexgagliano/mambaforge/envs/testastroquery/lib/python3.10/site-packages/astroquery/ipac/ned/core.py", line 749, in _check_ned_valid
    strdom = parseString(string)
  File "/Users/alexgagliano/mambaforge/envs/testastroquery/lib/python3.10/xml/dom/minidom.py", line 1998, in parseString
    return expatbuilder.parseString(string)
  File "/Users/alexgagliano/mambaforge/envs/testastroquery/lib/python3.10/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/Users/alexgagliano/mambaforge/envs/testastroquery/lib/python3.10/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 49
```
I'm running astroquery 0.4.6, astropy 5.3, and python 3.10.6. Thanks!

**Comment by bsipocz** [comment]
Thanks for reporting the versions. If you `pip install  --pre -U astroquery`, that picks up a newer release, the problem should be solved.

**Comment by alexandergagliano** [comment]
Fixed! Thanks.
