### ISSUE TITLE
BUG: CASDA timeout

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2768]
We've started to see CASDA timeouts, both in the tests and docs, e.g. 

```
_________________________________________________ [doctest] casda.rst __________________________________________________
018 The location should be specified in ICRS coordinates or an `astropy.coordinates.SkyCoord` object.
019 For example:
020 
021 .. doctest-remote-data::
022 
023     >>> from astroquery.casda import Casda
024     >>> from astropy.coordinates import SkyCoord
025     >>> from astropy import units as u
026     >>> centre = SkyCoord.from_name('NGC 7232')
027     >>> result_table = Casda.query_region(centre, radius=30*u.arcmin)
UNEXPECTED EXCEPTION: ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='casda.csiro.au', port=443): Read timed out. (read timeout=30)"))
Traceback (most recent call last):
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='casda.csiro.au', port=443): Read timed out. (read timeout=30)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/doctest.py", line 1350, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest casda.rst[4]>", line 1, in <module>
  File "/Users/bsipocz/munka/devel/astroquery/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/Users/bsipocz/munka/devel/astroquery/astroquery/utils/process_asyncs.py", line 26, in newmethod
    response = getattr(self, async_method_name)(*args, **kwargs)
  File "/Users/bsipocz/munka/devel/astroquery/astroquery/casda/core.py", line 130, in query_region_async
    response = self._request('GET', self.URL, params=request_payload,
  File "/Users/bsipocz/munka/devel/astroquery/astroquery/query.py", line 346, in _request
    response = query.request(self._session,
  File "/Users/bsipocz/munka/devel/astroquery/astroquery/query.py", line 74, in request
    return session.request(self.method, self.url, params=self.params,
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/bsipocz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='casda.csiro.au', port=443): Read timed out. (read timeout=30)

```

cc @jd-au

**Comment by jd-au** [comment]
Hi @bsipocz, We are aware of the issue and should have a fix in place on Monday. We've had to do some optimisation on the backend due to increasing data volumes.
Cheers,
James.

**Comment by jd-au** [comment]
The timeouts should be resolved now. Please let me know if you see further problems.

**Comment by bsipocz** [comment]
Thank you, I don't see other issues.
