### ISSUE TITLE
Horizons: Getting Sky_motion and Sky_mot_PA columns in obj.ephemerides() request

### ISSUE THREAD

**Issue by void4** [astropy/astroquery#2783]
I'm using astroquery 0.4.6

In the JPL Horizons [app](https://ssd.jpl.nasa.gov/horizons/app.html) interface, there is the option to get the apparent motion and position angle of an object, but these columns aren't returned by default by an [obj.ephemerides()](https://astroquery.readthedocs.io/en/latest/api/astroquery.jplhorizons.HorizonsClass.html#astroquery.jplhorizons.HorizonsClass.ephemerides) request, and I do not see an option to request them. ~~Must this be added to optional_settings={} perhaps?~~

Edit: Using quantities="47" fails with the following error:

```
Traceback (most recent call last):
  File "/home/test/.pyenv/versions/3.11.3/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/drs/main.py", line 209, in r_fastmpcheck
    vecs = get_jpl(objname, dt=obsdate, mpccode=mpccode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/drs/geteph.py", line 23, in get_jpl
    eph = obj.ephemerides(quantities="47")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.3/lib/python3.11/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.3/lib/python3.11/site-packages/astroquery/utils/process_asyncs.py", line 29, in newmethod
    result = self._parse_result(response, verbose=verbose)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.3/lib/python3.11/site-packages/astroquery/jplhorizons/core.py", line 1295, in _parse_result
    data = self._parse_horizons(response.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.3/lib/python3.11/site-packages/astroquery/jplhorizons/core.py", line 1256, in _parse_horizons
    data[col].unit = column_defs[col][1]
                     ^^^^^^^^^^^^^^^^^^^
KeyError: 'Sky_motion'

```

Edit: looks like this can be fixed by something like

```
from astroquery.jplhorizons import Horizons, conf

conf.eph_columns["Sky_motion"] = ("Sky_motion", "arcsec/minute")
conf.eph_columns["Sky_mot_PA"] = ("Sky_mot_PA", "°")
conf.eph_columns["RelVel-ANG"] = ("RelVel-ANG", "°")
```

(not sure if the units are correct there everywhere, but...)

So what's missing is column information in https://github.com/astropy/astroquery/blob/main/astroquery/jplhorizons/__init__.py#L40

**Comment by bsipocz** [comment]
@void4 - Based on your traceback, this could likely be an issue in `drs` or even something above it. Could you please post a failing example that is astroquery only?

Also, `optional_setting` is a new kwarg, so if you need to use it, please upgrade to a newer (dev) version, with `python -m pip install -U --pre astroquery`

**Comment by void4** [comment]
```python

from datetime import datetime, timezone

from astroquery.jplhorizons import Horizons
from astropy.time import Time

# The program will fail without these lines
#from astroquery.jplhorizons import conf
#conf.eph_columns["Sky_motion"] = ("Sky_motion", "arcsec/minute")
#conf.eph_columns["Sky_mot_PA"] = ("Sky_mot_PA", "°")
#conf.eph_columns["RelVel-ANG"] = ("RelVel-ANG", "°")

obj_id = 301#The moon, as an example
t_0 = datetime(2023, 7, 26, tzinfo=timezone.utc)
epochs = [Time(t_0).jd]

obj = Horizons(id=obj_id, location="500", epochs=epochs)
ephs = obj.ephemerides(quantities="1,3,38,47")
print(ephs)
```

fails with

```
$ python fail.py 
Traceback (most recent call last):
  File "/home/test/drs/fail.py", line 17, in <module>
    ephs = obj.ephemerides(quantities="1,3,38,47")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.3/lib/python3.11/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.3/lib/python3.11/site-packages/astroquery/utils/process_asyncs.py", line 29, in newmethod
    result = self._parse_result(response, verbose=verbose)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.3/lib/python3.11/site-packages/astroquery/jplhorizons/core.py", line 1295, in _parse_result
    data = self._parse_horizons(response.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.pyenv/versions/3.11.3/lib/python3.11/site-packages/astroquery/jplhorizons/core.py", line 1256, in _parse_horizons
    data[col].unit = column_defs[col][1]
                     ~~~~~~~~~~~^^^^^
KeyError: 'Sky_motion'
```
unless you uncomment the import and lines I added, then:

```
$ python fail.py 
targetname       datetime_str       datetime_jd solar_presence flags     RA       DEC     RA_rate    DEC_rate  RSS_3sigma  Sky_motion  Sky_mot_PA RelVel-ANG
   ---               ---                 d           ---        ---     deg       deg    arcsec / h arcsec / h   arcsec   arcsec / min    deg        deg    
---------- ------------------------ ----------- -------------- ----- --------- --------- ---------- ---------- ---------- ------------ ---------- ----------
Moon (301) 2023-Jul-26 00:00:00.000   2460151.5                      211.01153 -13.02612   1724.414   -800.004         --    31.682494  114.88791  -3.618887
```

**Comment by bsipocz** [comment]
cc @mkelley

**Comment by mkelley** [comment]
Thanks for reporting this issue.  The fix seems correct.  I have an update that will add these columns and a few others that are missing.

**Comment by void4** [comment]
(I'm not sure the units I used are correct, please double-check that)
