### ISSUE TITLE
MAST PanStarrs connection failing

### ISSUE THREAD

**Issue by odysseus9672** [astropy/astroquery#2822]
I'm using astroquery 0.4.5 with python 3.8. I'm limited to that version of Python by other packages, so I cannot update to an astroquery that requires a newer Python. When I try to query the MAST database to get PanStarrs photometry I am getting a connection error of some kind. I have two questions: 

1, is the MAST server malfunctioning?
2, if not, is there a bug in astroquery?

A simple session that produces the error is:
```
Seans-Work-Macbook-Pro:~ sean$ python3.8
Python 3.8.18 (default, Aug 25 2023, 02:23:15) 
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from astroquery.mast import Catalogs as MastCat
>>> import astropy.coordinates as apco
>>> import astropy.units as apun
>>> center = apco.SkyCoord(155.786632, 57.039094, unit=(apun.deg, apun.deg), frame="icrs")
>>> results = MastCat.query_region( center, radius=5.0*apun.arcsec, catalog="Panstarrs", data_release="dr2", table="stack", columns=['raStack', 'decStack', 'gKronFlux', 'gKronFluxErr', 'gKronRad', 'rKronFlux', 'rKronFluxErr', 'rKronRad', 'iKronFlux', 'iKronFluxErr', 'iKronRad', 'zKronFlux', 'zKronFluxErr', 'zKronRad', 'yKronFlux', 'yKronFluxErr', 'yKronRad'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/astroquery/utils/process_asyncs.py", line 26, in newmethod
    response = getattr(self, async_method_name)(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/astroquery/mast/collections.py", line 156, in query_region_async
    return self._current_connection.service_request_async(service, params, pagesize, page)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/astroquery/mast/services.py", line 273, in service_request_async
    response = self._request('POST', request_url, data=catalogs_request, headers=headers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/astroquery/mast/services.py", line 182, in _request
    response.raise_for_status()
  File "/Users/sean/Library/Python/3.8/lib/python/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://catalogs.mast.stsci.edu/api/v0.1/panstarrs/dr2/stack.json
>>> 
```

**Comment by odysseus9672** [comment]
This is a duplicate of issue #2709.
