### ISSUE TITLE
nasa ads throws error with example code

### ISSUE THREAD

**Issue by jvines** [astropy/astroquery#2926]
Hi, as the title says the nasa_ads query throws an error with the example code:

```python
results = ads.ADS.query_simple('^Persson Origin of water around deeply embedded low-mass protostars')
```

results in

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[28], line 1
----> 1 results = ads.ADS.query_simple('^Persson Origin of water around deeply embedded low-mass protostars')

File ~/opt/anaconda3/lib/python3.8/site-packages/astroquery/utils/class_or_instance.py:25, in class_or_instance.__get__.<locals>.f(*args, **kwds)
     23 def f(*args, **kwds):
     24     if obj is not None:
---> 25         return self.fn(obj, *args, **kwds)
     26     else:
     27         return self.fn(cls, *args, **kwds)

File ~/opt/anaconda3/lib/python3.8/site-packages/astroquery/nasa_ads/core.py:70, in ADSClass.query_simple(self, query_string, get_query_payload, get_raw_response, cache)
     68     return response
     69 # parse the XML response into AstroPy Table
---> 70 resulttable = self._parse_response(response.json())
     72 return resulttable

File ~/opt/anaconda3/lib/python3.8/site-packages/astroquery/nasa_ads/core.py:77, in ADSClass._parse_response(self, response)
     74 def _parse_response(self, response):
     76     try:
---> 77         response['response']['docs'][0]['bibcode']
     78     except IndexError:
     79         raise RuntimeError('No results returned!')

KeyError: 'bibcode'
```

**Comment by danehkar** [comment]
@keflavich I got the same error mentioned by @jvines 

 
```
                             access_url                             
---------------------------------------------------------------------
>>> results = na.ADS.query_simple('^Persson Origin of water around deeply embedded low-mass protostars')
Traceback (most recent call last):
  File "<python-input-22>", line 1, in <module>
    results = na.ADS.query_simple('^Persson Origin of water around deeply embedded low-mass protostars')
  File "~/anaconda3/lib/python3.13/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "~/anaconda3/lib/python3.13/site-packages/astroquery/nasa_ads/core.py", line 68, in query_simple
    resulttable = self._parse_response(response.json())
  File "~/anaconda3/lib/python3.13/site-packages/astroquery/nasa_ads/core.py", line 75, in _parse_response
    response['response']['docs'][0]['bibcode']
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'bibcode'
```

You need to correct the example as follows:

```
from astroquery import nasa_ads as na
# if you don't store your token as an environment variable
# or in a file, give it here
na.ADS.TOKEN = 'your-token-goes-here'
# by default, the top 10 records are returned, sorted in
# reverse chronological order. This can be changed
# change the number of rows returned
na.ADS.NROWS = 20
# change the sort order
na.ADS.SORT = 'bibcode desc'
# change the fields that are returned (enter as strings in a list)
na.ADS.ADS_FIELDS = ['author','title','abstract','pubdate','bibcode']
# the "^" makes ADS to return only papers where Persson
# is first author
results = na.ADS.query_simple('^Persson Origin of water around deeply embedded low-mass protostars')
results[0]["title"]
# to sort after publication date
results.sort(['pubdate'])
#  get the title of the last hit
title = results[-1]['title'][0]
# printout the authors of the last hit
print(results[-1]['author'])
```

Summary of changes:

na.ADS.ADS_FIELDS = ['author','title','abstract','pubdate'**,'bibcode'**]

results[0]**["title"]**

Now you can close this issue.

**Comment by bsipocz** [comment]
@keflavich - we really need to figure out a way to test these modules that need authentication. I mean we just kind of flying blind and hope for the best...

**Comment by keflavich** [comment]
Yeah, I hear you.  I don't think it's a super high priority at the moment though.

**Comment by bsipocz** [comment]
Yes, I don't mean this particular problem, but overall I think we need to push the services that require mandatory authentication to come up with a solution that we can then use in CI. Tokens or dummy test accounts or whatnot, but not being able to run tests is just not great.
