### ISSUE TITLE
BUG: 404 statuses from OAC

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2939]
cc @guillochon 

I saw that you've updated the URLs at https://github.com/astrocatalogs/OACAPI, but we did those already here and yet they started to 404. 

I really just wonder what the expected mid/long term expectations for the module are, whether we should add a deprecation warning on it that it might go away, etc.

**Comment by guillochon** [comment]
What exactly is 404ing?

**Comment by bsipocz** [comment]
> What exactly is 404ing?

'https://api.astrocats.space/', basically all the remote tests and docs examples here.

```
132 
133 The output is an Astropy table.
134 
135 The method get_spectra is designed to return all available spectra for an event
136 or list of events.
137 
138 .. doctest-remote-data::
139 
140     >>> from astroquery.oac import OAC
141     >>> spectra = OAC.get_spectra("SN2014J")
UNEXPECTED EXCEPTION: AttributeError('ERROR: The web service returned error code: 404')
Traceback (most recent call last):
  File "/Users/bsipocz/.pyenv/versions/3.12.1/lib/python3.12/doctest.py", line 1359, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest oac.rst[22]>", line 1, in <module>
  File "/Users/bsipocz/munka/devel/astroquery/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bsipocz/munka/devel/astroquery/astroquery/utils/process_asyncs.py", line 29, in newmethod
    result = self._parse_result(response, verbose=verbose)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bsipocz/munka/devel/astroquery/astroquery/oac/core.py", line 485, in _parse_result
    raise AttributeError("ERROR: The web service returned error code: %s" %
AttributeError: ERROR: The web service returned error code: 404
/Users/bsipocz/munka/devel/astroquery/docs/oac/oac.rst:141: UnexpectedException
```


```
ipdb> response.url
'https://api.astrocats.space/'
ipdb> response.status_code
404
ipdb> response.headers
{'Date': 'Thu, 01 Feb 2024 17:00:19 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=ot8st%2FYmu8u1cm%2FN2j52nzg2Q%2BN%2BwT5jWhLT9X97f3i4p08gj7aBqqLb5HQirYD%2FhqoOTjWYdcf01%2Bsio4gX8afuqfx5eTsTMLf132sIYOfDJU2pUfevtOMmLEAAAavH8ROdQFrDc0FtrUBqAaRbCXiC"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '84ebbffc390debb3-SEA', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400'}
```

**Comment by guillochon** [comment]
Our domain name provider recently had to change and some of the DNS settings got a little messed up. I believe I have fixed it now.

**Comment by bsipocz** [comment]
No more 404, I close this now.
