### ISSUE TITLE
Astroquery.mpc i = text_table.index('\n', text_table.index('h m s')) + 1 ValueError: substring not found

### ISSUE THREAD

**Issue by jurezakrajsek** [astropy/astroquery#3022]
There is another parsing issue in the mpc.get_ephemeris()

Some times MPC returns an empty table. Here is the result from the MPC website:
```
340P/Boattini
Perturbed ephemeris below is based on unperturbed elements from [MPEC 2021-N06](https://www.minorplanetcenter.net/mpec/K21/K21N06.html).
0340P
Date       UT      R.A. (J2000) Decl.    Delta     r     El.    Ph.   m1     Sky Motion        Object    Sun   Moon
            h m s                                                            "/hr     "/hr    Azi. Alt.  Alt.  Phase Dist. Alt.

```

In this case the _parse_result() function fails with this error
```
Traceback (most recent call last):
  File "E:\Jure\django-apps\cobs_dev\efemeride_new.py", line 264, in <module>
    main()
  File "E:\Jure\django-apps\cobs_dev\efemeride_new.py", line 86, in main
    eph = MPC.get_ephemeris(row.designation_packed,
  File "E:\Jure\django-apps\cobs_env\lib\site-packages\astroquery\utils\class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "E:\Jure\django-apps\cobs_env\lib\site-packages\astroquery\utils\process_asyncs.py", line 29, in newmethod
    result = self._parse_result(response, verbose=verbose)
  File "E:\Jure\django-apps\cobs_env\lib\site-packages\astroquery\mpc\core.py", line 1064, in _parse_result
    i = text_table.index('\n', text_table.index('h m s')) + 1
ValueError: substring not found
```

The code where the issue is coming from in the _parse_result() function of MPCClass in mpc/core.py:
```
if SKY:
    # slurp to newline after "h m s"
    i = text_table.index('\n', text_table.index('h m s')) + 1
    columns = text_table[:i]
    data_start = columns.count('\n') - 1
```

This can be easily managed by making a try and except around the code line: 
`i = text_table.index('\n', text_table.index('h m s')) + 1`
A similar scenario could happen also for JD_TT case (i guess) so i would put a try and except around that too.

Corrected code:
```
if SKY:
    # slurp to newline after "h m s"
    try:
        i = text_table.index('\n', text_table.index('h m s')) + 1
    except ValueError as e:
        raise InvalidQueryError(content)
    columns = text_table[:i]
    data_start = columns.count('\n') - 1
else:
    # slurp to newline after "JD_TT"
    try:
        i = text_table.index('\n', text_table.index('JD_TT')) + 1
    except ValueError as e:
        raise InvalidQueryError(content)
    columns = text_table[:i]
    data_start = columns.count('\n') - 1	
```

Best regards
Jure

**Comment by bsipocz** [comment]
cc @mkelley
