### ISSUE TITLE
Problem with NVAS Queries (astroquery.nvas)

### ISSUE THREAD

**Issue by RomanBurridge** [astropy/astroquery#3156]
I am Roman Burridge.  PhD Candidate at University of Hawaii at Manoa.

I am attempting to use astroquery.nvas.  Following the following example: https://github.com/astropy/astroquery/blob/main/docs/nvas/nvas.rst

```
>>> from astroquery.nvas import Nvas
>>> import astropy.units as u
>>> images = Nvas.get_images("3c 273", radius=2*u.arcsec, band="K", max_rms=500)
```
And here is the error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 666, in urlopen     
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1001, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 164, in _new_conn       
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7f556929c520>, 'Connection to webtest.aoc.nrao.edu timed out. (connect timeout=60)')   

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 720, in urlopen     
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 438, in increment       
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webtest.aoc.nrao.edu', port=443): Max retries exceeded with url: /cgi-bin/lsjouwer/archive-pos.pl (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f556929c520>, 'Connection to webtest.aoc.nrao.edu timed out. (connect timeout=60)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peacesea/.local/lib/python3.8/site-packages/astroquery/nvas/core.py", line 74, in get_images
    readable_objs = self.get_images_async(
  File "/home/peacesea/.local/lib/python3.8/site-packages/astroquery/nvas/core.py", line 125, in get_images_async
    image_urls = self.get_image_list(
  File "/home/peacesea/.local/lib/python3.8/site-packages/astroquery/nvas/core.py", line 188, in get_image_list
    response = self._request("POST", url=Nvas.URL, data=request_payload,
  File "/home/peacesea/.local/lib/python3.8/site-packages/astroquery/query.py", line 375, in _request
    response = query.request(self._session,
  File "/home/peacesea/.local/lib/python3.8/site-packages/astroquery/query.py", line 77, in request
    return session.request(self.method, self.url, params=self.params,
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 535, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 648, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='webtest.aoc.nrao.edu', port=443): Max retries exceeded with url: /cgi-bin/lsjouwer/archive-pos.pl (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f556929c520>, 'Connection to webtest.aoc.nrao.edu timed out. (connect timeout=60)'))
```

**Comment by bsipocz** [comment]
cc @keflavich - could you have a look into this? Looks like webtest.aoc.nrao.edu is offline? I haven't dug back when it started, but at first sight it looks like either a server URL change or server side outage related

**Comment by RomanBurridge** [comment]
webtest.aoc.nrao.edu still appears to be offline and I am getting the same issue.

**Comment by RomanBurridge** [comment]
I updated astroquery however I get the same issue as before.  I assume that I will need to wait some time for astroquery to come out with a new update, is this correct?  If so, how long will I have to wait?  Sorry for my naiveness.

**Comment by bsipocz** [comment]
Yes, the isn't any release out with this yet. You can easily install the dev version though with:
`pip install -U git+https://github.com/astropy/astroquery`
