### ISSUE TITLE
Vizier exception unclosed token

### ISSUE THREAD

**Issue by letmaik** [astropy/astroquery#465]
I'm not sure if this is a bug in astroquery or something odd on my machine:

``` python
from astroquery.vizier.core import Vizier
import astropy.coordinates as coord
import astropy.units as u

column_filters = {}
row_limit = 3600
radius = 44.7297340808
centerRa = 55.4474526803
centerDec = -8.88299326657
catalog = 'I/259/tyc2'
v = Vizier(columns=['_RAJ2000', '_DEJ2000', '+VTmag'],
       column_filters=column_filters, 
       row_limit=row_limit)
result = v.query_region(coord.SkyCoord(ra=centerRa, dec=centerDec,
                                       unit=(u.deg, u.deg),
                                       frame='icrs'), 
                        radius=radius*u.deg, catalog=catalog)[0]
```

On one machine it fails:

```
site-packages/astroquery/vizier/core.py:556: UserWarning: VOTABLE parsing raised exception: 
  warnings.warn("VOTABLE parsing raised exception: {0}".format(ex))
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "site-packages/astroquery/utils/class_or_instance.py", line 24, in <lambda>
    f = lambda *args, **kwds: self.fn(obj, *args, **kwds)
  File "site-packages/astroquery/utils/process_asyncs.py", line 31, in newmethod
    result = self._parse_result(response, verbose=verbose)
  File "site-packages/astroquery/vizier/core.py", line 589, in _parse_result
    "Exception: " + str(self.table_parse_error))
astroquery.exceptions.TableParseError: Failed to parse VIZIER result! The raw response can be found in self.response, and the error in self.table_parse_error.  The attempted parsed result is in self.parsed_result.
Exception: 3665:48: unclosed token
```

On another though it works. Same Python and astroquery version.

When I print out `v.response.text` of the failing one I get at the end:

```
22.2</TD><TD>15.3</TD><TD>8.641</TD><TD>20742</TD><TD>66.67107778</TD><TD>-6.40412444</TD></TR>\n<TR><TD>56.472790</TD><TD>0.222691</TD><TD>7.594</T'
```

So it's cut off for some reason. `len(v.response.text)` is 683903. Debugging on the machine where it works I can see a complete response:

```
<TD>71.14089944</TD><TD>-16.06510583</TD></TR>
</TABLEDATA></DATA>
</TABLE>
</RESOURCE>
</VOTABLE>
```

The response length here is 687123.

**Comment by bsipocz** [comment]
@keflavich @letmaik - What's the status of this, did the workaround work? There wasn't much update on this, and the original example works for me, so probably we can close this?

**Comment by keflavich** [comment]
:+1: to closing.  The `cache` kwarg is included in vizier now too.
