### ISSUE TITLE
Change invalid='raise' to invalid='exception' in vizier.core.parse_vizier_votable?

### ISSUE THREAD

**Issue by evertrol** [astropy/astroquery#607]
Querying a Vizier table leads to an odd (because empty) warning:

For example:

```python
from astroquery.vizier import Vizier
from astropy.coordinates import SkyCoord
from astropy import units
Vizier.query_region(SkyCoord(0, 0, unit=units.degree), width=1*units.degree, 
                    catalog='I/284')
```
results in

```
/usr/local/lib/python3.5/site-packages/astroquery-0.3.dev3057-py3.5.egg/astroquery/vizier/core.py:685: UserWarning: VOTABLE parsing raised exception: 
  warnings.warn("VOTABLE parsing raised exception: {0}".format(ex))
```

and the exception string appears to be empty.

Re-raising the caught exception, instead of turning it into a warning, results in the chained exception below, which reveals the likely issue: `votable.parse` uses `invalid='raise'` instead of `invalid='exception'`. I assume the acceptable keyword values have changed somewhere along the way in astropy, but this has not yet been updated here.

Changing this into `invalid='exception'` here (and a few lines below as well), makes the warning disappear, since the actual exception that was caught is an AssertionError.

If this seems the correct solution, I'd be happy to make a PR for it.

NB: a quick search only reveals the two cases in `vizier.core.parse_vizier_votable` with `invalid='raise'`.
<hr>
Full traceback of the uncaught exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/astroquery-0.3.dev3057-py3.5.egg/astroquery/vizier/core.py", line 624, in _parse_result
    get_catalog_names=get_catalog_names)
  File "/usr/local/lib/python3.5/site-packages/astroquery-0.3.dev3057-py3.5.egg/astroquery/vizier/core.py", line 683, in parse_vizier_votable
    vo_tree = votable.parse(tf, pedantic=False, invalid='raise')
  File "/usr/local/lib/python3.5/site-packages/astropy/io/votable/table.py", line 120, in parse
    assert invalid in ('exception', 'mask')
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testquery.py", line 5, in <module>
    Vizier.query_region(SkyCoord(0, 0, unit=units.degree), width=1*units.degree, catalog='I/284')
  File "/usr/local/lib/python3.5/site-packages/astroquery-0.3.dev3057-py3.5.egg/astroquery/utils/class_or_instance.py", line 24, in <lambda>
    f = lambda *args, **kwds: self.fn(obj, *args, **kwds)
  File "/usr/local/lib/python3.5/site-packages/astroquery-0.3.dev3057-py3.5.egg/astroquery/utils/process_asyncs.py", line 31, in newmethod
    result = self._parse_result(response, verbose=verbose)
  File "/usr/local/lib/python3.5/site-packages/astroquery-0.3.dev3057-py3.5.egg/astroquery/vizier/core.py", line 631, in _parse_result
    "Exception: " + str(self.table_parse_error))
astroquery.exceptions.TableParseError: Failed to parse VIZIER result! The raw response can be found in self.response, and the error in self.table_parse_error.  The attempted parsed result is in self.parsed_result.
Exception: 
```

**Comment by keflavich** [comment]
Indeed, could you make this a PR?

[votable.parse docs](http://stsdas.stsci.edu/astrolib/vo/html/api_table.html#vo.table.parse)
