### ISSUE TITLE
ALMA upstream unicode error

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#737]
There is a bug in the returns from ALMA queries that results in unicode decode errors:

```
In [3]: Alma.query(payload={'pi_name':'Ginsburg'}, public=False)
Out[3]: Traceback (most recent call last):
  File "/Users/adam/repos/ipython.git/IPython/core/formatters.py", line 699, in __call__
    printer.pretty(obj)
  File "/Users/adam/repos/ipython.git/IPython/lib/pretty.py", line 383, in pretty
    return _default_pprint(obj, self, cycle)
  File "/Users/adam/repos/ipython.git/IPython/lib/pretty.py", line 503, in _default_pprint
    _repr_pprint(obj, p, cycle)
  File "/Users/adam/repos/ipython.git/IPython/lib/pretty.py", line 694, in _repr_pprint
    output = repr(obj)
  File "/Users/adam/repos/astropy/astropy/table/table.py", line 812, in __repr__
    return self._base_repr_(html=False, max_width=None)
  File "/Users/adam/repos/astropy/astropy/table/table.py", line 799, in _base_repr_
    max_lines=max_lines, tableclass=tableclass)
  File "/Users/adam/repos/astropy/astropy/table/pprint.py", line 478, in _pformat_table
    align=align_)
  File "/Users/adam/repos/astropy/astropy/table/pprint.py", line 224, in _pformat_col
    col_strs = list(col_strs_iter)
  File "/Users/adam/repos/astropy/astropy/table/pprint.py", line 392, in _pformat_col_iter
    col_str = format_func(col_format, col[i])
  File "/Users/adam/repos/astropy/astropy/table/pprint.py", line 24, in default_format_func
    return val.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 0: invalid start byte
```

I tracked this down to an incorrect type specification in one of the votable rows.  The temporary workaround until it is fixed upstream is to not attempt to print that column (unfortunately, that also means you can't access it):

```
rslt = Alma.query_region(testCoord, 1*u.deg)
print(rslt['Project code', 'Source name', 'RA', 'Dec', 'Spatial resolution', 'Frequency resolution', 'Integration', 'Release date', 'Frequency support', 'Velocity resolution', 'Pol products', 'Observation date', 'PI name', 'PWV', 'Group ous id', 'Member ous id', 'Asdm uid', 'Project title', 'Project type', 'Scan intent', 'Largest angular scale', 'QA2 Status', 'Pub'])
```

The bad column is `band`

**Comment by keflavich** [comment]
Closed by #775
